<?php
defined('_JEXEC') or die();
JImport('b0.Accessory.AccessoryIds');
JImport('b0.Sparepart.SparepartIds');
JImport('b0.Work.WorkIds');

class FeedConfigFeeds
{
	public const FEED_CONFIG_FEEDS = [
		'accesories-vesta' => [
			'isNeed' => true,
			'name' => 'Аксессуары Веста',
			'filePath' => '/uploads/feeds/feed-accessories-vesta.xml',
			'sectionId' => [AccessoryIds::ID_SECTION],
//			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => [AccessoryIds::ID_MODEL],
			'modelName' => ['Lada Vesta'],
			'limit' => 0,
		],
		'accesories-xray' => [
			'isNeed' => true,
			'name' => 'Аксессуары XRay',
			'filePath' => '/uploads/feeds/feed-accessories-xray.xml',
			'sectionId' => [AccessoryIds::ID_SECTION],
//			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => [AccessoryIds::ID_MODEL],
			'modelName' => ['Lada XRay'],
			'limit' => 0,
		],
		'accesories-granta' => [
			'isNeed' => true,
			'name' => 'Аксессуары Гранта',
			'filePath' => '/uploads/feeds/feed-accessories-granta.xml',
			'sectionId' => [AccessoryIds::ID_SECTION],
//			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => [AccessoryIds::ID_MODEL],
			'modelName' => ['Lada Granta FL'],
			'limit' => 0,
		],
		'accesories-largus' => [
			'isNeed' => true,
			'name' => 'Аксессуары Ларгус',
			'filePath' => '/uploads/feeds/feed-accessories-largus.xml',
			'sectionId' => [AccessoryIds::ID_SECTION],
//			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => [AccessoryIds::ID_MODEL],
			'modelName' => ['Lada Largus'],
			'limit' => 0,
		],
/*		'accesories-iskra' => [
			'isNeed' => true,
			'name' => 'Аксессуары Искра',
			'filePath' => '/uploads/feeds/feed-accessories-iskra.xml',
			'sectionId' => AccessoryIds::ID_SECTION,
			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => AccessoryIds::ID_MODEL,
			'modelName' => 'Lada Iskra',
			'limit' => 0,
		],*/
		'spareparts-vesta' => [
			'isNeed' => true,
			'name' => 'Запчасти Веста',
			'filePath' => '/uploads/feeds/feed-spareparts-vesta.xml',
			'sectionId' => [SparepartIds::ID_SECTION],
//			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => [SparepartIds::ID_MODEL],
			'modelName' => ['Lada Vesta'],
			'limit' => 0,
		],
		'spareparts-xray' => [
			'isNeed' => true,
			'name' => 'Запчасти XRay',
			'filePath' => '/uploads/feeds/feed-spareparts-xray.xml',
			'sectionId' => [SparepartIds::ID_SECTION],
//			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => [SparepartIds::ID_MODEL],
			'modelName' => ['Lada XRay'],
			'limit' => 0,
		],
		'spareparts-granta' => [
			'isNeed' => true,
			'name' => 'Запчасти Гранта',
			'filePath' => '/uploads/feeds/feed-spareparts-granta.xml',
			'sectionId' => [SparepartIds::ID_SECTION],
//			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => [SparepartIds::ID_MODEL],
			'modelName' => ['Lada Granta FL'],
			'limit' => 0,
		],
		'spareparts-largus' => [
			'isNeed' => true,
			'name' => 'Запчасти Ларгус',
			'filePath' => '/uploads/feeds/feed-spareparts-largus.xml',
			'sectionId' => [SparepartIds::ID_SECTION],
//			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => [SparepartIds::ID_MODEL],
			'modelName' => ['Lada Largus'],
			'limit' => 0,
		],
/*		'spareparts-iskra' => [
			'isNeed' => true,
			'name' => 'Запчасти Искра',
			'filePath' => '/uploads/feeds/feed-spareparts-iskra.xml',
			'sectionId' => SparepartIds::ID_SECTION,
			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => SparepartIds::ID_MODEL,
			'modelName' => 'Lada Iskra',
			'limit' => 0,
		],*/
        'products-vesta' => [
            'isNeed' => true,
            'name' => 'Запчасти и аксессуары Веста',
            'filePath' => '/uploads/feeds/feed-products-vesta.xml',
            'sectionId' => [SparepartIds::ID_SECTION, AccessoryIds::ID_SECTION],
//			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
            'fieldModel' => [SparepartIds::ID_MODEL, AccessoryIds::ID_MODEL],
            'modelName' => ['Lada Vesta'],
            'limit' => 0,
        ],
        'products-xray' => [
            'isNeed' => true,
            'name' => 'Запчасти и аксессуары XRay',
            'filePath' => '/uploads/feeds/feed-products-xray.xml',
            'sectionId' => [SparepartIds::ID_SECTION, AccessoryIds::ID_SECTION],
//			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
            'fieldModel' => [SparepartIds::ID_MODEL, AccessoryIds::ID_MODEL],
            'modelName' => ['Lada XRay'],
            'limit' => 0,
        ],
        'products-granta' => [
            'isNeed' => true,
            'name' => 'Запчасти и аксессуары Гранта',
            'filePath' => '/uploads/feeds/feed-products-granta.xml',
            'sectionId' => [SparepartIds::ID_SECTION, AccessoryIds::ID_SECTION],
//			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
            'fieldModel' => [SparepartIds::ID_MODEL, AccessoryIds::ID_MODEL],
            'modelName' => ['Lada Granta FL'],
            'limit' => 0,
        ],
        'products-largus' => [
            'isNeed' => true,
            'name' => 'Запчасти и аксессуары Ларгус',
            'filePath' => '/uploads/feeds/feed-products-largus.xml',
            'sectionId' => [SparepartIds::ID_SECTION, AccessoryIds::ID_SECTION],
//			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
            'fieldModel' => [SparepartIds::ID_MODEL, AccessoryIds::ID_MODEL],
            'modelName' => ['Lada Largus'],
            'limit' => 0,
        ],
        'works-vesta' => [
            'isNeed' => true,
            'name' => 'Работы Веста',
            'filePath' => '/uploads/feeds/feed-works-vesta.xml',
            'sectionId' => [WorkIds::ID_SECTION],
//            'fieldAvailability' => 1,
            'fieldModel' => [WorkIds::ID_MODEL],
            'modelName' => ['Lada Vesta'],
            'limit' => 0,
        ],
        'works-xray' => [
            'isNeed' => true,
            'name' => 'Работы XRay',
            'filePath' => '/uploads/feeds/feed-works-xray.xml',
            'sectionId' => [WorkIds::ID_SECTION],
//            'fieldAvailability' => 1,
            'fieldModel' => [WorkIds::ID_MODEL],
            'modelName' => ['Lada XRay'],
            'limit' => 0,
        ],
        'works-granta' => [
            'isNeed' => true,
            'name' => 'Работы Гранта',
            'filePath' => '/uploads/feeds/feed-works-granta.xml',
            'sectionId' => [WorkIds::ID_SECTION],
//            'fieldAvailability' => 1,
            'fieldModel' => [WorkIds::ID_MODEL],
            'modelName' => ['Lada Granta FL'],
            'limit' => 0,
        ],
        'works-largus' => [
            'isNeed' => true,
            'name' => 'Работы Ларгус',
            'filePath' => '/uploads/feeds/feed-works-largus.xml',
            'sectionId' => [WorkIds::ID_SECTION],
//            'fieldAvailability' => 1,
            'fieldModel' => [WorkIds::ID_MODEL],
            'modelName' => ['Lada Largus'],
            'limit' => 0,
        ],
        'works-all' => [
            'isNeed' => true,
            'name' => 'Работы общий',
            'filePath' => '/uploads/feeds/feed-works-all.xml',
            'sectionId' => [WorkIds::ID_SECTION],
//            'fieldAvailability' => 1,
            'fieldModel' => [WorkIds::ID_MODEL],
            'modelName' => ['Lada Vesta', 'Lada XRay', 'Lada Granta FL', 'Lada Largus'],
            'limit' => 0,
        ],
    ];
}
