<?php
defined('_JEXEC') or die();
JImport('b0.Accessory.AccessoryIds');
JImport('b0.Sparepart.SparepartIds');

class FeedConfigFeeds
{
	public const FEED_CONFIG_FEEDS = [
		'accesories-vesta' => [
			'isNeed' => true,
			'name' => 'Аксессуары Веста',
			'filePath' => '/uploads/feeds/feed-accessories-vesta.xml',
			'sectionId' => AccessoryIds::ID_SECTION,
			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => AccessoryIds::ID_MODEL,
			'modelName' => 'Lada Vesta',
			'limit' => 0,
		],
		'accesories-xray' => [
			'isNeed' => true,
			'name' => 'Аксессуары XRay',
			'filePath' => '/uploads/feeds/feed-accessories-xray.xml',
			'sectionId' => AccessoryIds::ID_SECTION,
			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => AccessoryIds::ID_MODEL,
			'modelName' => 'Lada XRay',
			'limit' => 0,
		],
		'accesories-granta' => [
			'isNeed' => true,
			'name' => 'Аксессуары Гранта',
			'filePath' => '/uploads/feeds/feed-accessories-granta.xml',
			'sectionId' => AccessoryIds::ID_SECTION,
			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => AccessoryIds::ID_MODEL,
			'modelName' => 'Lada Granta FL',
			'limit' => 0,
		],
		'accesories-largus' => [
			'isNeed' => true,
			'name' => 'Аксессуары Ларгус',
			'filePath' => '/uploads/feeds/feed-accessories-largus.xml',
			'sectionId' => AccessoryIds::ID_SECTION,
			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => AccessoryIds::ID_MODEL,
			'modelName' => 'Lada Largus',
			'limit' => 0,
		],
		'accesories-moskvich' => [
			'isNeed' => true,
			'name' => 'Аксессуары Москвич',
			'filePath' => '/uploads/feeds/feed-accessories-moskvich.xml',
			'sectionId' => AccessoryIds::ID_SECTION,
			'fieldAvailability' => AccessoryIds::ID_IS_BY_ORDER,
			'fieldModel' => AccessoryIds::ID_MODEL,
			'modelName' => 'Москвич',
			'limit' => 0,
		],
		'spareparts-vesta' => [
			'isNeed' => true,
			'name' => 'Запчасти Веста',
			'filePath' => '/uploads/feeds/feed-spareparts-vesta.xml',
			'sectionId' => SparepartIds::ID_SECTION,
			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => SparepartIds::ID_MODEL,
			'modelName' => 'Lada Vesta',
			'limit' => 0,
		],
		'spareparts-xray' => [
			'isNeed' => true,
			'name' => 'Запчасти XRay',
			'filePath' => '/uploads/feeds/feed-spareparts-xray.xml',
			'sectionId' => SparepartIds::ID_SECTION,
			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => SparepartIds::ID_MODEL,
			'modelName' => 'Lada XRay',
			'limit' => 0,
		],
		'spareparts-granta' => [
			'isNeed' => true,
			'name' => 'Запчасти Гранта',
			'filePath' => '/uploads/feeds/feed-spareparts-granta.xml',
			'sectionId' => SparepartIds::ID_SECTION,
			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => SparepartIds::ID_MODEL,
			'modelName' => 'Lada Granta FL',
			'limit' => 0,
		],
		'spareparts-largus' => [
			'isNeed' => true,
			'name' => 'Запчасти Ларгус',
			'filePath' => '/uploads/feeds/feed-spareparts-largus.xml',
			'sectionId' => SparepartIds::ID_SECTION,
			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => SparepartIds::ID_MODEL,
			'modelName' => 'Lada Largus',
			'limit' => 0,
		],
		'spareparts-moskvich' => [
			'isNeed' => true,
			'name' => 'Запчасти Москвич',
			'filePath' => '/uploads/feeds/feed-spareparts-moskvich.xml',
			'sectionId' => SparepartIds::ID_SECTION,
			'fieldAvailability' => SparepartIds::ID_IS_BY_ORDER,
			'fieldModel' => SparepartIds::ID_MODEL,
			'modelName' => 'Москвич',
			'limit' => 0,
		],
	];
}
